#!/usr/bin/env bash

BIN_NAME=$(basename "$0")
COMMAND=$1 # Command entered - install or refresh
BRANCH=$2  # The branch name or commit reference can be passed as the second argument
PROJECT="dotFiles"
REPO1="marana@git.kuzcotopia.io:marana/${PROJECT}.git"
REPO1_NAME="Kuzcotopia"
REPO2="git@github.com:heymarkarana/${PROJECT}.git"
REPO2_NAME="GitHub"
DEFAULT_REPO="${REPO1}" # Default repository
SELECTED_REPO="${DEFAULT_REPO}"
TARGET="${HOME}/.dotFiles"

# Function to show help information
show_help() {
  echo
  echo
  echo "Usage: ${BIN_NAME} <command> [branch] [--repo <repository>]"
  echo
  echo "Commands:"
  echo "   install                    Set up .dotFiles from scratch"
  echo "   install [branch]           Specify a branch to install or refresh"
  echo "                              (default: main)"
  echo "   refresh [--hard]           Refresh .dotFiles: use git pull or a hard reset "
  echo "                              (if --hard is provided)"
  echo
  echo "Options:"
  echo "   --repo <repository>         Specify the repository to clone from "
  echo "                               (default: ${DEFAULT_REPO})"
  echo
  echo -e "\033[1;4mRefreshing to a specific branch:\033[0m"
  echo "If you want to refresh (pull the latest changes) from a specific branch, "
  echo "you can pass the branch name as the first argument after refresh. The script "
  echo "will use this branch for the pull operation."
  echo -e "\033[0;32m./script_name refresh <branch_name>\033[0m"  echo
  echo
  echo -e "\033[1;4mHard reset to a specific branch:\033[0m"
  echo "If you want to perform a hard reset to a specific branch (which deletes the "
  echo "current .dotFiles directory and reclones the specified branch), you can pass "
  echo "--hard followed by the branch name."
  echo -e "\033[0;32m./script_name refresh --hard <branch_name>\033[0m"
  echo
  echo
}
# Parse additional arguments
parse_arguments() {
  while [[ $# -gt 0 ]]; do
    case $1 in
      --repo)
        SELECTED_REPO=$2
        shift # Consume argument value
        ;;
      *)
        ;;
    esac
    shift
  done
}

# Function to switch shell
switch_to_zsh() {
  local current_shell
  current_shell=$(getent passwd "$USER" | cut -d: -f7)
  local zsh_path
  zsh_path=$(command -v zsh)

  if [[ "${current_shell}" != "${zsh_path}" ]]; then
    echo "Changing default shell to ZSH..."
    if chsh -s "${zsh_path}"; then
      echo "Default shell changed to ZSH."
      echo "Please log out and back in for the change to take effect."
      echo "Or run 'zsh' manually to switch to ZSH for this session."

      read -r -p "Would you like to switch to ZSH for this session? [y/N] " response
      if [[ "${response}" =~ ^[Yy]$ ]]; then
        exec "${zsh_path}" -l
      fi
    else
      echo "Failed to change default shell. You can manually run: chsh -s $(command -v zsh)"
    fi
  else
    echo "ZSH is already your default shell."
  fi
}

# Function to install Homebrew on macOS
install_homebrew() {
  if [[ "$(uname)" == "Darwin" ]]; then
    if ! command -v brew &>/dev/null; then
      echo "Installing Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      if ! grep -q "eval \"\$(/opt/homebrew/bin/brew shellenv)\"" "${HOME}/.zshrc"; then
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> "${HOME}/.zshrc"
      fi

      eval "$(/opt/homebrew/bin/brew shellenv)"
      echo "Homebrew installation complete."
    else
      echo "Homebrew is already installed."
    fi
  else
    echo "Skipping Homebrew installation: not on macOS."
  fi
}

# Function to install ZSH
install_zsh() {
  if command -v zsh &>/dev/null; then
    touch "${HOME}/.zshrc"
    echo "ZSH is already installed."
  else
    echo "Installing ZSH..."
    sudo apt update -q && sudo apt install -y zsh
    touch "${HOME}/.zshrc"
    echo "ZSH installation complete."
  fi
}

# Function to set up dotFiles
install_dotfiles() {
  echo "Setting up .dotFiles..."
  install_homebrew
  install_zsh

  BRANCH=${BRANCH:-"master"}

  echo "Cloning dotFiles from ${SELECTED_REPO}..."
  if git clone --branch "${BRANCH}" "${SELECTED_REPO}" "${TARGET}"; then
    echo "dotFiles download complete."
    cd "${TARGET}"
    switch_to_zsh
  else
    echo "Git clone failed. Exiting."
    exit 1
  fi
}

# Function to refresh dotFiles
refresh_dotfiles() {
  echo "Refreshing .dotFiles..."
  local branch="${1:-main}"

  if [[ "${branch}" == "--hard" ]]; then
    branch="${2:-main}"
    echo "Performing a hard reset to branch ${branch}..."
    rm -rf "${TARGET}"
    git clone --branch "${branch}" "${SELECTED_REPO}" "${TARGET}" || {
      echo "Failed to clone repository. Exiting."
      exit 1
    }
  else
    echo "Pulling latest updates from branch ${branch}..."
    cd "${TARGET}" || exit 1
    git pull origin "${branch}" || {
      echo "Failed to pull updates. Exiting."
      exit 1
    }
  fi
}

# Main script logic
parse_arguments "$@"
case ${COMMAND} in
  "" | "-h" | "--help")
    show_help
    ;;
  install)
    # Ensure the bootstrap script exists and is executable
    if [[ -x "${HOME}/.bootstrap/GitHarness.sh" ]]; then
      "${HOME}/.bootstrap/GitHarness.sh"
    fi
    install_dotfiles

    ;;
  refresh)
    refresh_dotfiles "$2"
    ;;
  *)
    echo "Unknown command: ${COMMAND}" >&2
    show_help
    exit 1
    ;;
esac